export const SOURCE_STATUS = {
  IMPLEMENTED: "implemented",
  NEEDS_KEY: "needs_key",
  COMMERCIAL: "commercial",
  MANUAL: "manual",
  UNVERIFIED: "unverified",
  NEEDS_SETUP: "needs_setup",
};

export const sourceCatalog = [
  {
    id: "github",
    name: "GitHub",
    region: "overseas",
    category: "open_source",
    status: SOURCE_STATUS.IMPLEMENTED,
    trust: 0.82,
    env: "GITHUB_TOKEN",
    docs: "https://docs.github.com/en/rest/search/search",
    notes: "公共搜索无需 key，低限流；token 只用于提高限额。star/fork 是关注与协作信号，不等同用户数。",
  },
  {
    id: "hackernews",
    name: "Hacker News / Show HN",
    region: "overseas",
    category: "community",
    status: SOURCE_STATUS.IMPLEMENTED,
    trust: 0.74,
    env: "",
    docs: "https://github.com/HackerNews/API",
    notes: "Firebase API 无需 key。points/comments 是早期兴趣和讨论热度，不等同付费或留存。",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    region: "overseas",
    category: "model_ecosystem",
    status: SOURCE_STATUS.IMPLEMENTED,
    trust: 0.72,
    env: "HF_TOKEN",
    docs: "https://huggingface.co/docs/hub/api",
    notes: "公开模型/数据集 API 可采。downloads/likes 是生态使用线索，需和下游证据合并判断。",
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    region: "overseas",
    category: "launch",
    status: SOURCE_STATUS.NEEDS_KEY,
    trust: 0.68,
    env: "PRODUCTHUNT_TOKEN",
    docs: "https://api.producthunt.com/v2/docs",
    notes: "GraphQL API 需要 token。upvote/comment 只能证明 launch 关注。",
  },
  {
    id: "reddit",
    name: "Reddit",
    region: "overseas",
    category: "community",
    status: SOURCE_STATUS.NEEDS_KEY,
    trust: 0.62,
    env: "REDDIT_CLIENT_ID, REDDIT_CLIENT_SECRET",
    docs: "https://www.reddit.com/dev/api/",
    notes: "OAuth 后可采 subreddit 讨论。需去重营销帖和转发。",
  },
  {
    id: "x",
    name: "X / Twitter",
    region: "overseas",
    category: "social",
    status: SOURCE_STATUS.COMMERCIAL,
    trust: 0.55,
    env: "X_BEARER_TOKEN",
    docs: "https://developer.x.com/en/docs",
    notes: "API 通常需要付费档位；转发链与 bot 噪声高，默认置信度较低。",
  },
  {
    id: "wechat",
    name: "微信公众号文章",
    region: "china",
    category: "media",
    status: SOURCE_STATUS.NEEDS_SETUP,
    automatic: true,
    trust: 0.58,
    env: "",
    docs: "https://github.com/cooderl/wewe-rss",
    notes: "通过 WeWe RSS 自动同步已订阅公众号文章。首次扫码并添加公众号，后续无需粘贴正文；不是全微信搜索。",
  },
  {
    id: "xiaohongshu",
    name: "小红书",
    region: "china",
    category: "social",
    status: SOURCE_STATUS.NEEDS_SETUP,
    automatic: true,
    trust: 0.48,
    env: "XHS_MCP_TOKEN（服务鉴权可选）",
    docs: "https://github.com/xpzouying/xiaohongshu-mcp",
    notes: "连接 xiaohongshu-mcp，扫码后按关键词搜索并读取笔记详情；登录过期与限流会明确报错。",
  },
  {
    id: "douyin",
    name: "抖音",
    region: "china",
    category: "social_video",
    status: SOURCE_STATUS.NEEDS_SETUP,
    automatic: true,
    trust: 0.46,
    env: "",
    docs: "https://github.com/DIYgod/RSSHub/tree/master/lib/routes/douyin",
    notes: "RSSHub 博主订阅，需配置用户路由和带浏览器的服务；平台验证可能影响采集。",
  },
  {
    id: "bilibili",
    name: "B站",
    region: "china",
    category: "video",
    status: SOURCE_STATUS.NEEDS_SETUP,
    automatic: true,
    trust: 0.54,
    env: "",
    docs: "https://github.com/DIYgod/RSSHub/tree/master/lib/routes/bilibili",
    notes: "RSSHub 自动同步 UP 主或其他已配置订阅路由；可用范围取决于路由和上游状态。",
  },
  {
    id: "jike",
    name: "即刻",
    region: "china",
    category: "community",
    status: SOURCE_STATUS.NEEDS_SETUP,
    automatic: true,
    trust: 0.5,
    env: "",
    docs: "https://github.com/DIYgod/RSSHub/tree/master/lib/routes/jike",
    notes: "RSSHub 自动订阅圈子或用户动态；首次选择跟踪目标，后续自动同步。",
  },
  {
    id: "zhihu",
    name: "知乎",
    region: "china",
    category: "community",
    status: SOURCE_STATUS.NEEDS_SETUP,
    automatic: true,
    trust: 0.52,
    env: "",
    docs: "https://github.com/DIYgod/RSSHub/tree/master/lib/routes/zhihu",
    notes: "RSSHub 自动订阅作者回答、专栏或问题；部分路由需要在 RSSHub 配置 ZHIHU_COOKIES。",
  },
  {
    id: "36kr",
    name: "36氪 / 创投媒体",
    region: "china",
    category: "venture_media",
    status: SOURCE_STATUS.NEEDS_SETUP,
    automatic: true,
    trust: 0.64,
    env: "",
    docs: "https://github.com/DIYgod/RSSHub/tree/master/lib/routes/36kr",
    notes: "通过 RSSHub 自动读取新闻订阅，按关键词筛选；媒体报道仅作为研究线索。",
  },
  {
    id: "vc_accelerator",
    name: "投资机构 / 孵化器项目名单",
    region: "mixed",
    category: "venture",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.66,
    env: "",
    docs: "https://www.ycombinator.com/companies",
    notes: "YC、a16z、红杉、奇绩等名单可作为发现入口，不能单独证明产品成立。",
  },
  {
    id: "company_site",
    name: "公司 / 产品官网",
    region: "mixed",
    category: "owned",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.5,
    env: "",
    docs: "",
    notes: "官网是公司自述。适合抽取定位、客户 logo、定价、API 文档，但需标注 self-reported。",
  },
  {
    id: "changelog",
    name: "更新日志 / API 文档",
    region: "mixed",
    category: "owned_technical",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.6,
    env: "",
    docs: "",
    notes: "高频更新支持交付能力判断；仍不能替代采用和收入证据。",
  },
  {
    id: "jobs",
    name: "招聘页",
    region: "mixed",
    category: "hiring",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.6,
    env: "",
    docs: "",
    notes: "岗位方向可辅助规模化条件和 GTM 阶段，不能直接推导营收。",
  },
  {
    id: "appstore",
    name: "App Store / Chrome 扩展商店",
    region: "mixed",
    category: "distribution",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.62,
    env: "",
    docs: "https://chromewebstore.google.com/",
    notes: "评分、评论、安装量区间可辅助采用持续性；第一版手动导入。",
  },
  {
    id: "traffic_vendor",
    name: "流量 / 融资数据供应商",
    region: "mixed",
    category: "commercial_data",
    status: SOURCE_STATUS.COMMERCIAL,
    trust: 0.7,
    env: "SIMILARWEB_API_KEY, CRUNCHBASE_API_KEY",
    docs: "https://developer.similarweb.com/",
    notes: "常需商业授权；第三方估算必须和事实、自述分开显示。",
  },
  {
    id: "web_search_general",
    name: "通用网页搜索 / 新闻搜索",
    region: "mixed",
    category: "discovery",
    status: SOURCE_STATUS.UNVERIFIED,
    trust: 0.44,
    env: "",
    docs: "",
    notes: "预留入口；第一版未实现和未验证，不参与自动采集。可用于后续接入合规搜索 API。",
  },
];

export function getSource(id) {
  return sourceCatalog.find((source) => source.id === id);
}

export function implementedSourceIds() {
  return sourceCatalog
    .filter((source) => source.status === SOURCE_STATUS.IMPLEMENTED || source.automatic)
    .map((source) => source.id);
}
