export const SOURCE_STATUS = {
  IMPLEMENTED: "implemented",
  NEEDS_KEY: "needs_key",
  COMMERCIAL: "commercial",
  MANUAL: "manual",
  UNVERIFIED: "unverified",
};

export const sourceCatalog = [
  {
    id: "github",
    name: "GitHub",
    region: "overseas",
    category: "open_source",
    status: SOURCE_STATUS.IMPLEMENTED,
    trust: 0.82,
    env: "GITHUB_TOKEN",
    docs: "https://docs.github.com/en/rest/search/search",
    notes: "公共搜索无需 key，低限流；token 只用于提高限额。star/fork 是关注与协作信号，不等同用户数。",
  },
  {
    id: "hackernews",
    name: "Hacker News / Show HN",
    region: "overseas",
    category: "community",
    status: SOURCE_STATUS.IMPLEMENTED,
    trust: 0.74,
    env: "",
    docs: "https://github.com/HackerNews/API",
    notes: "Firebase API 无需 key。points/comments 是早期兴趣和讨论热度，不等同付费或留存。",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    region: "overseas",
    category: "model_ecosystem",
    status: SOURCE_STATUS.IMPLEMENTED,
    trust: 0.72,
    env: "HF_TOKEN",
    docs: "https://huggingface.co/docs/hub/api",
    notes: "公开模型/数据集 API 可采。downloads/likes 是生态使用线索，需和下游证据合并判断。",
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    region: "overseas",
    category: "launch",
    status: SOURCE_STATUS.NEEDS_KEY,
    trust: 0.68,
    env: "PRODUCTHUNT_TOKEN",
    docs: "https://api.producthunt.com/v2/docs",
    notes: "GraphQL API 需要 token。upvote/comment 只能证明 launch 关注。",
  },
  {
    id: "reddit",
    name: "Reddit",
    region: "overseas",
    category: "community",
    status: SOURCE_STATUS.NEEDS_KEY,
    trust: 0.62,
    env: "REDDIT_CLIENT_ID, REDDIT_CLIENT_SECRET",
    docs: "https://www.reddit.com/dev/api/",
    notes: "OAuth 后可采 subreddit 讨论。需去重营销帖和转发。",
  },
  {
    id: "x",
    name: "X / Twitter",
    region: "overseas",
    category: "social",
    status: SOURCE_STATUS.COMMERCIAL,
    trust: 0.55,
    env: "X_BEARER_TOKEN",
    docs: "https://developer.x.com/en/docs",
    notes: "API 通常需要付费档位；转发链与 bot 噪声高，默认置信度较低。",
  },
  {
    id: "wechat",
    name: "微信公众号文章",
    region: "china",
    category: "media",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.58,
    env: "",
    docs: "https://developers.weixin.qq.com/doc/offiaccount/Getting_Started/Overview.html",
    notes: "公开网页采集受限；第一版支持 URL+正文手动导入，并标注转载/自述属性。",
  },
  {
    id: "xiaohongshu",
    name: "小红书",
    region: "china",
    category: "social",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.48,
    env: "",
    docs: "https://www.xiaohongshu.com/",
    notes: "无稳定公开内容 API；建议人工导入或商业数据供应商。",
  },
  {
    id: "douyin",
    name: "抖音",
    region: "china",
    category: "social_video",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.46,
    env: "",
    docs: "https://developer.open-douyin.com/",
    notes: "开放平台偏经营/授权账号能力，不等于全站搜索。第一版手动导入。",
  },
  {
    id: "bilibili",
    name: "B站",
    region: "china",
    category: "video",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.54,
    env: "",
    docs: "https://openhome.bilibili.com/",
    notes: "开放能力以账号/内容合作为主；公开讨论需人工导入或第三方授权。",
  },
  {
    id: "jike",
    name: "即刻",
    region: "china",
    category: "community",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.5,
    env: "",
    docs: "https://web.okjike.com/",
    notes: "无公开采集 API。适合人工导入主题讨论和创始人动态。",
  },
  {
    id: "zhihu",
    name: "知乎",
    region: "china",
    category: "community",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.52,
    env: "",
    docs: "https://www.zhihu.com/",
    notes: "无稳定公开搜索 API；第一版按手动材料处理。",
  },
  {
    id: "36kr",
    name: "36氪 / 创投媒体",
    region: "china",
    category: "venture_media",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.64,
    env: "",
    docs: "https://36kr.com/",
    notes: "融资、采访和榜单需区分第三方报道与公司自述；第一版手动导入。",
  },
  {
    id: "vc_accelerator",
    name: "投资机构 / 孵化器项目名单",
    region: "mixed",
    category: "venture",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.66,
    env: "",
    docs: "https://www.ycombinator.com/companies",
    notes: "YC、a16z、红杉、奇绩等名单可作为发现入口，不能单独证明产品成立。",
  },
  {
    id: "company_site",
    name: "公司 / 产品官网",
    region: "mixed",
    category: "owned",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.5,
    env: "",
    docs: "",
    notes: "官网是公司自述。适合抽取定位、客户 logo、定价、API 文档，但需标注 self-reported。",
  },
  {
    id: "changelog",
    name: "更新日志 / API 文档",
    region: "mixed",
    category: "owned_technical",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.6,
    env: "",
    docs: "",
    notes: "高频更新支持交付能力判断；仍不能替代采用和收入证据。",
  },
  {
    id: "jobs",
    name: "招聘页",
    region: "mixed",
    category: "hiring",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.6,
    env: "",
    docs: "",
    notes: "岗位方向可辅助规模化条件和 GTM 阶段，不能直接推导营收。",
  },
  {
    id: "appstore",
    name: "App Store / Chrome 扩展商店",
    region: "mixed",
    category: "distribution",
    status: SOURCE_STATUS.MANUAL,
    trust: 0.62,
    env: "",
    docs: "https://chromewebstore.google.com/",
    notes: "评分、评论、安装量区间可辅助采用持续性；第一版手动导入。",
  },
  {
    id: "traffic_vendor",
    name: "流量 / 融资数据供应商",
    region: "mixed",
    category: "commercial_data",
    status: SOURCE_STATUS.COMMERCIAL,
    trust: 0.7,
    env: "SIMILARWEB_API_KEY, CRUNCHBASE_API_KEY",
    docs: "https://developer.similarweb.com/",
    notes: "常需商业授权；第三方估算必须和事实、自述分开显示。",
  },
  {
    id: "web_search_general",
    name: "通用网页搜索 / 新闻搜索",
    region: "mixed",
    category: "discovery",
    status: SOURCE_STATUS.UNVERIFIED,
    trust: 0.44,
    env: "",
    docs: "",
    notes: "预留入口；第一版未实现和未验证，不参与自动采集。可用于后续接入合规搜索 API。",
  },
];

export function getSource(id) {
  return sourceCatalog.find((source) => source.id === id);
}

export function implementedSourceIds() {
  return sourceCatalog
    .filter((source) => source.status === SOURCE_STATUS.IMPLEMENTED)
    .map((source) => source.id);
}
